### ISSUE TITLE
There's an official plugin now

### ISSUE THREAD

**Issue by pepicrft** [cprecioso/asdf-tuist#3]
Hola @cprecioso,

First of all, thanks for contributing to the Tuist community with an asdf plugin. As you might know, we are making rtx the default installer and version management for Tuist, so we implemented an [official plugin](https://github.com/asdf-community/asdf-tuist) and moved it to the `asdf-community` organization on GitHub. If I had known that you implemented a plugin, I wouldn't have duplicated efforts 😬 (note to self: do a quick search on GitHub before doing anything).

I [opened a PR](https://github.com/asdf-vm/asdf-plugins/pull/933) on the `asdf-plugins` repository changing the reference to the official plugin. I hope you don't mind that we are taking the maintenance responsibility from you :).

**Comment by cprecioso** [comment]
Sure
